version: "3.2"
services:
  web:
    build:
      context: . # Current directory!
    ports:
      - "8088:8088"
      - "5678:5678"
    restart: always
    volumes:
      - ".:/home/joycloud/joycloud"
    depends_on:
      - redis
    command: [ "python3.8","-m", "debugpy",  "--listen", "0.0.0.0:5678", "manage.py", "runserver", "0.0.0.0:8088", "--nothreading", "--noreload"]

  # nginx:
  #   image: "nginx:1-alpine"
  #   restart: always
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web
  #   volumes:
  #     - ./joycloud_nginx_local:/etc/nginx/conf.d/default.conf
  #     - ".:/home/joycloud/joycloud"
  #     - "../front_site:/home/joycloud/frontend"

  redis:
    image: "redis:6-alpine"
    restart: always
    ports:
      - 6379:6379

  # rqworker:
  #   build:
  #     context: . # Current directory!
  #   restart: always
  #   volumes:
  #     - ".:/home/joycloud/joycloud"
  #   command: ["python3.8", "manage.py", "rqworker", "default", "fragment"]
